import 'dart:convert';

FichaModel fichaFromJson(String str) => FichaModel.fromJson(json.decode(str));

String fichaToJson(FichaModel data) => json.encode(data.toJson());

class FichaModel {
  FichaModel(
      {this.id,
      this.codid,
      this.nombre,
      this.fechanac,
      this.direccion,
      this.ident,
      this.telefono,
      this.mail,
      this.fecha,
      this.diagnostico,
      this.motivo,
      this.enfermedadActual,
      this.antGo,
      this.antPyf,
      this.pulso,
      this.temp,
      this.pa,
      this.peso,
      this.cabeza,
      this.abdomen,
      this.extrem,
      this.torax,
      this.pelvis,
      this.tratamiento,
      this.evolucion,
      this.sucid,
      this.proid,
      this.pacid});

  int id, codid, proid, sucid, pacid;
  String pulso, temp, pa, peso, direccion, ident, telefono, fechanac, mail;
  String nombre,
      fecha,
      diagnostico,
      motivo,
      enfermedadActual,
      antGo,
      antPyf,
      cabeza,
      abdomen,
      extrem,
      torax,
      pelvis,
      tratamiento,
      evolucion;

  factory FichaModel.fromJson(Map<String, dynamic> json) => FichaModel(
        id: json["FIC_ID"],
        codid: json["FIC_COD_ID"],
        nombre: json["PER_NOMBRE"],
        fechanac: json["PER_FEC_NAC"],
        direccion: json["PER_DIRECCION"],
        ident: json["PER_IDENT"],
        telefono: json["PER_TELEFONO"],
        mail: json["PER_MAIL"],
        fecha: json["FIC_FECHA"],
        diagnostico: json["FIC_DIAGNOSTICO"],
        motivo: json["FIC_MOTIVO"],
        enfermedadActual: json["FIC_ENFER_ACT"],
        antGo: json["FIC_ANT_GO"],
        antPyf: json["FIC_ANT_PYF"],
        pulso: json["FIC_PULSO"],
        temp: json["FIC_TEMP"],
        pa: json["FIC_PA"],
        peso: json["FIC_PESO"],
        cabeza: json["FIC_CABEZA"],
        abdomen: json["FIC_ABDOMEN"],
        extrem: json["FIC_EXTREM"],
        torax: json["FIC_TORAX"],
        pelvis: json["FIC_PELVIS"],
        tratamiento: json["FIC_TRATAMIENTO"],
        evolucion: json["FIC_EVOLUCION"],
        sucid: json["SUC_ID"],
        proid: json["PRO_ID"],
        pacid: json["PAC_ID"],
      );

  Map<String, dynamic> toJson() => {
        "FIC_ID": id,
        "FIC_COD_ID": proid,
        "PER_NOMBRE": nombre,
        "PER_DIRECCION": direccion,
        "PER_IDENT": ident,
        "PER_TELEFONO": telefono,
        "PER_MAIL": mail,
        "FIC_FECHA": fecha,
        "FIC_DIAGNOSTICO": diagnostico,
        "FIC_MOTIVO": motivo,
        "FIC_ENFER_ACT": enfermedadActual,
        "FIC_ANT_GO": antGo,
        "FIC_ANT_PYF": antPyf,
        "FIC_PULSO": pulso,
        "FIC_TEMP": temp,
        "FIC_PA": pa,
        "FIC_PESO": peso,
        "FIC_CABEZA": cabeza,
        "FIC_ABDOMEN": abdomen,
        "FIC_EXTREM": extrem,
        "FIC_TORAX": torax,
        "FIC_PELVIS": pelvis,
        "FIC_TRATAMIENTO": tratamiento,
        "FIC_EVOLUCION": evolucion,
        "SUC_ID": sucid,
        "PRO_ID": proid,
        "PAC_ID": pacid
      };
}
